import type { Metadata } from "next";
import { ColorSchemeScript } from "@mantine/core";
import "@mantine/core/styles.css";
import Provider from "../utilities/provider";
import { RootStyleRegistry } from "./EmotionRootStyleRegistry";
import { MantineEmotionProvider } from "@mantine/emotion";
import UserStoreProvider from "@/providers/userStoreProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
        />
      </head>
      <body suppressHydrationWarning={true}>
        <RootStyleRegistry>
          <Provider>
            <MantineEmotionProvider>
              <UserStoreProvider>{children}</UserStoreProvider>
            </MantineEmotionProvider>
          </Provider>
        </RootStyleRegistry>
      </body>
    </html>
  );
}
